import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import TopNav from "./components/TopNav/TopNav";
import LeftNav from "./components/LeftNav/LeftNav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Test",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="w-full h-screen overflow-hidden">
          <TopNav />
          <div className="flex h-full">
            <LeftNav />
            <div className="App overflow-auto w-full p-5">{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
